I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 3, in script call
    call s0
  File "game/script/Season0/season0.rpy", line 6, in script call
    call s0s5
  File "game/script/Season0/s0s5.rpy", line 47, in script
    unknwon "You have only 2 hours, and time is ticking, so hurry! To claim your prize, simply tell us your name and credit card information after the beep! Terms and conditions apply!"
Exception: Sayer 'unknwon' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 3, in script call
    call s0
  File "game/script/Season0/season0.rpy", line 6, in script call
    call s0s5
  File "game/script/Season0/s0s5.rpy", line 47, in script
    unknwon "You have only 2 hours, and time is ticking, so hurry! To claim your prize, simply tell us your name and credit card information after the beep! Terms and conditions apply!"
  File "C:\Users\Tingxuan\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Tingxuan\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'unknwon' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
IdolGameDemo 1.0
Tue Nov 28 17:16:20 2023
